/*
 * Copyright (c) KleinerHacker alias Pfeiffer C Soft 2026.
 * This work is licensed under the Apache License, Version 2.0.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, this software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations.
 */

package org.pcsoft.app.aighost.app

import javafx.scene.text.Font

/**
 * Central access point for the type faces shipped with the application.
 *
 * The application carries its own font so that the lettering looks the same on every platform. Ghost
 * Writer is a geometric, monolinear sans with rounded terminals that follows the `AI` lettering of
 * the project logo. Its outlines are generated by the vector generator under `tools/font`.
 *
 * The resource path lives here exactly once, the same way [AiGhostIcons] owns the icon file names and
 * [AiGhostTheme] owns the stylesheet, so no other place in the code base names the font file.
 *
 * [install] registers the font with JavaFX; afterwards [FAMILY] can be used wherever a font family is
 * expected.
 */
object AiGhostFonts {

    /** Resource path of the shipped regular weight. */
    const val REGULAR_PATH: String = "/fonts/GhostWriter-Regular.ttf"

    /** Family name the registered font is known by inside JavaFX. */
    const val FAMILY: String = "Ghost Writer"

    private var installed: Boolean = false

    /**
     * Registers the shipped font with the JavaFX font system.
     *
     * Calling this more than once is safe - the font is loaded only on the first call, so the family
     * never appears twice in the list of known families.
     */
    fun install() {
        if (installed) {
            return
        }

        val resource = requireNotNull(AiGhostFonts::class.java.getResourceAsStream(REGULAR_PATH)) {
            "Font resource not found: $REGULAR_PATH"
        }
        resource.use { stream ->
            requireNotNull(Font.loadFont(stream, -1.0)) {
                "Font could not be loaded: $REGULAR_PATH"
            }
        }
        installed = true
    }
}
